#!/bin/bash
## This line is a comment, the following lines are for Moab
#MOAB -l nodes=1
#MOAB -l walltime=4:00:00
#MOAB -N script
#MOAB -j oe

#MSUB -l advres=b1002
#MSUB -A b1002

##### These are shell commands. Note that all MSUB commands come first.


cd $PBS_O_WORKDIR
module load python/Canopy 


ulimit -s unlimited



python fourier_analysis.py 'out_lk/' 800 50 
##python fourier_analysis.py 'out_sg_noind/' 921 50
##python fourier_analysis.py 'out_sg_test_hi/' 403 50
